export const OREDER_CREATE_REQUEST = "OREDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const OREDER_DETAILS_REQUEST = "OREDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const OREDER_PAY_REQUEST = "OREDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const OREDER_LIST_MY_REQUEST = "OREDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const OREDER_LIST_REQUEST = "OREDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const OREDER_DELEVER_REQUEST = "OREDER_DELEVER_REQUEST";
export const ORDER_DELEVER_SUCCESS = "ORDER_DELEVER_SUCCESS";
export const ORDER_DELEVER_FAIL = "ORDER_DELEVER_FAIL";
export const ORDER_DELEVER_RESET = "ORDER_DELEVER_RESET";
